// LOCALHOST 
GET http://localhost:8080/contacts
GET http://localhost:8080/contacts/644c1562d0b2ed679586b3d7
GET http://localhost:8080/contacts/644c15e9d0b2ed679586b3d8
GET http://localhost:8080/contacts/644c1630d0b2ed679586b3d9

// PRODUCTION Deploy - need to fix these
# GET https://cse341-instructor.herokuapp.com/contacts 
# GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
# GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
# GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4